name: "transformer_med_hpc_l40"

model:
  type: "transformer"
  vocab_size: 4000
  model_dim: 1024
  n_layers: 12
  dropout: 0.15
  n_heads: 8
  context_length: 2048

optimiser:
  type: "adam"
  lr: 0.00015

loss_function:
  type: "cross_entropy"

training:
  epochs: 50
  device: "cuda"

data:
  train_dataset_dir: "/home/joshua/data/mimic_meds/mimic_iv_meds/tokenized_data/ethos_timetokens/train"
  val_dataset_dir: "/home/joshua/data/mimic_meds/mimic_iv_meds/tokenized_data/ethos_timetokens/tuning"
  vocab_path: "/home/joshua/data/mimic_meds/mimic_iv_meds/tokenized_data/ethos_timetokens/vocab.csv"
  sequence_length: 2048
  batch_size: 64
  shuffle: true
